name: reportrash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  cloud_firestore: ^5.0.1
  easy_localization: ^3.0.7
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  go_router: ^14.1.4
  google_maps_flutter: ^2.7.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  share_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/logo/
  - assets/img/
  - assets/translations/