// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAel2O0IaWOXOVc0j1XVJzZl-Ked6qd2bo',
    appId: '1:186044340160:web:fd819fa994bcaefbc3da25',
    messagingSenderId: '186044340160',
    projectId: 'reportrashv2',
    authDomain: 'reportrashv2.firebaseapp.com',
    storageBucket: 'reportrashv2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf0QG4oQQXilkmAVF5oGwBU613LgDpe-k',
    appId: '1:186044340160:android:803a68509c26b23fc3da25',
    messagingSenderId: '186044340160',
    projectId: 'reportrashv2',
    storageBucket: 'reportrashv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ5E2RHufWNCApugkk5G4_Ql8qn-snfMQ',
    appId: '1:186044340160:ios:6c7ec8e9e0b731f3c3da25',
    messagingSenderId: '186044340160',
    projectId: 'reportrashv2',
    storageBucket: 'reportrashv2.appspot.com',
    iosBundleId: 'com.pulsedigital.reportrash',
  );
}
